import assert from "node:assert/strict";
import { WeChatTypingIndicators } from "../lib/wechat-typing.ts";
const flush = () => new Promise<void>((resolve) => setImmediate(resolve));
const calls: Array<[string, number]> = [];
const errors: unknown[] = [];
let releaseStart!: () => void;
let slow = true;
const typing = new WeChatTypingIndicators(async (user, status) => {
  calls.push([user, status]);
  if (slow && status === 1) await new Promise<void>((resolve) => { releaseStart = resolve; });
}, (err) => { errors.push(err); }, 10);
const a = typing.acquire("phone");
const b = typing.acquire("phone");
assert.deepEqual(calls, [["phone", 1]], "overlapping jobs share start");
a(); a();
assert.equal(calls.length, 1, "release is idempotent and another task remains");
b();
assert.equal(calls.length, 1, "stop waits for in-flight start");
slow = false;
releaseStart();
await flush();
assert.deepEqual(calls, [["phone", 1], ["phone", 2]]);
const c = typing.acquire("phone");
await new Promise((resolve) => setTimeout(resolve, 35));
assert.ok(calls.filter(([, status]) => status === 1).length >= 3, "long jobs refresh typing state");
c();
await flush();
assert.deepEqual(calls.at(-1), ["phone", 2]);
const d = typing.acquire("other");
typing.stop();
await flush();
d();
assert.deepEqual(calls.at(-1), ["other", 2]);
assert.equal(errors.length, 0);
console.log("微信输入状态测试通过：立即启动、并发引用、心跳续期、迟到请求、幂等结束及停止清理。");
