import assert from "node:assert/strict";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
const root = await fs.mkdtemp(path.join(os.tmpdir(), "deerhux-wechat-mirror-"));
process.env.DEERHUX_CODING_AGENT_DIR = root;
process.env.PI_CODING_AGENT_DIR = root;
const { WeChatBotService } = await import("../lib/wechat-bot.ts");
const { getAgentEventStore } = await import("../lib/agent-runtime/event-store.ts");
const bot = new WeChatBotService(root);
const originalFetch = globalThis.fetch;
let endPoll!: (response: Response) => void;
let polling: Promise<void> | undefined;
const outbound: Array<{ msg: { from_user_id: string; to_user_id: string; context_token: string; run_id?: string; item_list: Array<{ type: number; is_completed?: boolean; text_item?: { text: string }; tool_call_start_item?: { tool_name: string; tool_call_id: string }; tool_call_result_item?: { tool_name: string; tool_call_id: string; status: string } }> } }> = [];
try {
  bot.loginWithCredentials({ botToken: "fixture", baseUrl: "http://127.0.0.1:1", accountId: "bot", userId: "phone" });
  await fs.writeFile(path.join(root, "wechat/user-sessions.json"), JSON.stringify({ phone: "desktop" }));
  await fs.writeFile(path.join(root, "wechat/context-tokens.json"), JSON.stringify({ "bot:phone": "fixture-context" }));
  globalThis.fetch = async (input, init) => {
    if (String(input).endsWith("getupdates")) return new Promise((resolve) => { endPoll = resolve; });
    if (String(input).endsWith("getconfig")) return Response.json({ ret: 0, typing_ticket: "fixture-ticket" });
    if (String(input).endsWith("sendtyping")) return Response.json({ ret: 0 });
    assert.ok(String(input).endsWith("sendmessage"));
    outbound.push(JSON.parse(String(init?.body)));
    return Response.json({ ret: 0 });
  };
  polling = bot.startPolling();
  const store = getAgentEventStore();
  const emit = (event: { type: string; [key: string]: unknown }, turnId = "desktop:t1") => store.append({ sessionId: "desktop", runId: "desktop", turnId, event });
  emit({ type: "message_end", message: { role: "user", content: "从电脑输入", clientMessageId: "client-one" } });
  emit({ type: "tool_execution_start", toolCallId: "read-1", toolName: "read", args: { path: "private" } });
  emit({ type: "tool_execution_start", toolCallId: "read-1", toolName: "read" });
  emit({ type: "tool_execution_end", toolCallId: "read-1", toolName: "read", isError: false, result: "private" });
  emit({ type: "tool_execution_end", toolCallId: "read-1", toolName: "read", isError: false });
  emit({ type: "message_end", message: { role: "assistant", content: [{ type: "text", text: "最终回答" }] } });
  emit({ type: "agent_end" });
  await (bot as unknown as { mirror: { drain(): Promise<void> } }).mirror.drain();
  assert.deepEqual(outbound.filter((body) => body.msg.item_list[0].type === 1).map((body) => body.msg.item_list[0].text_item?.text), ["【电脑端】\n从电脑输入", "【工具进度】正在执行：read", "【工具进度】执行完成：read", "【AI 回复】\n最终回答"]);
  assert.ok(outbound.every((body) => body.msg.from_user_id === "" && body.msg.to_user_id === "phone" && body.msg.context_token === "fixture-context"));
  assert.deepEqual(outbound.map((body) => body.msg.item_list[0].type), [1, 1, 1, 1]);
  assert.equal(outbound[1].msg.run_id, "desktop:t1");
  assert.equal(outbound[2].msg.run_id, "desktop:t1");
  assert.ok(!JSON.stringify(outbound).includes("private"));
  assert.ok(bot.getStatus().lastRepliedAt);
  emit({ type: "message_end", message: { role: "user", content: "微信输入", clientMessageId: "wechat:one" } }, "desktop:t2");
  emit({ type: "message_end", message: { role: "user", content: "微信输入" } }, "desktop:t2");
  emit({ type: "message_end", message: { role: "assistant", content: [{ type: "text", text: "由原链路发回" }] } }, "desktop:t2");
  emit({ type: "tool_execution_start", toolCallId: "bash-1", toolName: "bash" }, "desktop:t2");
  emit({ type: "tool_execution_end", toolCallId: "bash-1", toolName: "bash", isError: true }, "desktop:t2");
  emit({ type: "agent_end" }, "desktop:t2");
  await (bot as unknown as { mirror: { drain(): Promise<void> } }).mirror.drain();
  assert.equal(outbound.length, 6);
  assert.deepEqual(outbound.slice(4).map((body) => body.msg.item_list[0].type), [1, 1]);
  assert.equal(outbound[5].msg.item_list[0].text_item?.text, "【工具进度】执行失败：bash");
  bot.stopPolling();
  emit({ type: "message_end", message: { role: "user", content: "停止之后", clientMessageId: "client-two" } }, "desktop:t3");
  await Promise.resolve();
  assert.equal(outbound.length, 6);
  console.log("微信同步集成测试通过：服务端事件到发送报文、上下文令牌、消息顺序、微信去重与停止解绑监听。");
} finally {
  bot.stopPolling();
  endPoll?.(Response.json({ ret: 0 }));
  await polling;
  globalThis.fetch = originalFetch;
  await fs.rm(root, { recursive: true, force: true });
}
